// flow-typed signature: 6d600b3d1221beea72f0de76a103819c
// flow-typed version: <<STUB>>/mobx-react_v^3.5.8/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react/custom' {
  declare module.exports: any;
}

declare module 'mobx-react/native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react/custom.js' {
  declare module.exports: $Exports<'mobx-react/custom'>;
}
declare module 'mobx-react/index' {
  declare module.exports: $Exports<'mobx-react'>;
}
declare module 'mobx-react/index.js' {
  declare module.exports: $Exports<'mobx-react'>;
}
declare module 'mobx-react/native.js' {
  declare module.exports: $Exports<'mobx-react/native'>;
}
