// flow-typed signature: 231c04eb0e26c7582464b42ef043b23c
// flow-typed version: <<STUB>>/double-ended-queue_v^2.1.0-0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'double-ended-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'double-ended-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'double-ended-queue/Gruntfile' {
  declare module.exports: any;
}

declare module 'double-ended-queue/js/deque' {
  declare module.exports: any;
}

// Filename aliases
declare module 'double-ended-queue/Gruntfile.js' {
  declare module.exports: $Exports<'double-ended-queue/Gruntfile'>;
}
declare module 'double-ended-queue/js/deque.js' {
  declare module.exports: $Exports<'double-ended-queue/js/deque'>;
}
