// flow-typed signature: cc07527d477ee1012104506efdacb33e
// flow-typed version: <<STUB>>/flow-runtime_v^0.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-runtime/config/eslint' {
  declare module.exports: any;
}

declare module 'flow-runtime/config/rollup.config.browser' {
  declare module.exports: any;
}

declare module 'flow-runtime/config/rollup.config.commonjs' {
  declare module.exports: any;
}

declare module 'flow-runtime/config/rollup.config.es2015' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime.es2015' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime.min' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/mocha' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/eslint-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/mobx_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/mobx-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ThisType/thisTypeInClassMethod' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ThisType/thisTypeInClassMethodRecorded' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/fixtures' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/fixtures.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/annotateValue' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/cache' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/classDecorators' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/compareTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/cyclic' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/Declaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ExtendsDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ModuleDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ModuleExportsDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/TypeDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/VarDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/decorateFunction' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/decorateFunction.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/decorateGeneratorFunction' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorMessages' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/__tests__/makeJSONError.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/__tests__/makeTypeError.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/makeJSONError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/makeTypeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/makeWarningMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/RuntimeTypeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$DiffType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$FlowFixMeType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$KeysType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$ObjMapiType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$ObjMapType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$ShapeType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$SubType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/$SuperType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/ClassType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/flowTypes/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/getErrorMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/globalContext' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/invariant' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeReactPropTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeUnion' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/primitiveTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerBuiltins' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerPrimitiveTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerTypePredicates' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/symbols' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/typeConstraints' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/typeConstraints.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/TypeContext' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/typed.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/TypeInferrer' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/TypeInferrer.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/AnyType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ArrayType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/BooleanLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/BooleanType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/EmptyType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ExistentialType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FlowIntoType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionTypeParam' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionTypeRestParam' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionTypeReturn' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/GeneratorType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/GenericType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/IntersectionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/MixedType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NullableType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NullLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NumberType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NumericLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectTypeCallProperty' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectTypeIndexer' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectTypeProperty' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ParameterizedFunctionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ParameterizedTypeAlias' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/PartialType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/RefinementType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/StringLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/StringType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/SymbolLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/SymbolType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ThisType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TupleType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/Type' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeAlias' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeBox' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeConstructor' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeParameter' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeParameterApplication' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeReference' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/UnionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/VoidType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/Validation' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ThisType/thisTypeInClassMethod' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/__fixtures__/ThisType/thisTypeInClassMethodRecorded' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/fixtures' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/__tests__/fixtures.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/annotateValue' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/cache' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/classDecorators' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/compareTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/cyclic' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/Declaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/ExtendsDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/ModuleDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/ModuleExportsDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/TypeDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/declarations/VarDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/decorateFunction' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/decorateFunction.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/decorateGeneratorFunction' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorMessages' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorReporting/__tests__/makeJSONError.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorReporting/__tests__/makeTypeError.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorReporting/makeJSONError' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorReporting/makeTypeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorReporting/makeWarningMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/errorReporting/RuntimeTypeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$DiffType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$FlowFixMeType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$KeysType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$ObjMapiType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$ObjMapType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$ShapeType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$SubType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/$SuperType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/ClassType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/flowTypes/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/getErrorMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/globalContext' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/index.cjs' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/invariant' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/makeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/makeReactPropTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/makeUnion' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/primitiveTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/registerBuiltins' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/registerPrimitiveTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/registerTypePredicates' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/symbols' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/typeConstraints' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/typeConstraints.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/TypeContext' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/typed.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/TypeInferrer' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/TypeInferrer.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/AnyType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ArrayType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/BooleanLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/BooleanType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/EmptyType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ExistentialType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/FlowIntoType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/FunctionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/FunctionTypeParam' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/FunctionTypeRestParam' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/FunctionTypeReturn' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/GeneratorType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/GenericType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/IntersectionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/MixedType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/NullableType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/NullLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/NumberType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/NumericLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ObjectType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ObjectTypeCallProperty' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ObjectTypeIndexer' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ObjectTypeProperty' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ParameterizedFunctionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ParameterizedTypeAlias' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/PartialType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/RefinementType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/StringLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/StringType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/SymbolLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/SymbolType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/ThisType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TupleType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/Type' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TypeAlias' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TypeBox' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TypeConstructor' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TypeParameter' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TypeParameterApplication' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/TypeReference' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/UnionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/types/VoidType' {
  declare module.exports: any;
}

declare module 'flow-runtime/src/Validation' {
  declare module.exports: any;
}

declare module 'flow-runtime/test-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-runtime/config/eslint.js' {
  declare module.exports: $Exports<'flow-runtime/config/eslint'>;
}
declare module 'flow-runtime/config/rollup.config.browser.js' {
  declare module.exports: $Exports<'flow-runtime/config/rollup.config.browser'>;
}
declare module 'flow-runtime/config/rollup.config.commonjs.js' {
  declare module.exports: $Exports<'flow-runtime/config/rollup.config.commonjs'>;
}
declare module 'flow-runtime/config/rollup.config.es2015.js' {
  declare module.exports: $Exports<'flow-runtime/config/rollup.config.es2015'>;
}
declare module 'flow-runtime/dist/flow-runtime.es2015.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.es2015'>;
}
declare module 'flow-runtime/dist/flow-runtime.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime'>;
}
declare module 'flow-runtime/dist/flow-runtime.min.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.min'>;
}
declare module 'flow-runtime/flow-typed/mocha.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/mocha'>;
}
declare module 'flow-runtime/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/eslint-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/eslint-plugin-flow_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/mobx_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/mobx_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/mobx-react_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/mobx-react_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/mocha_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/mocha_vx.x.x'>;
}
declare module 'flow-runtime/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ThisType/thisTypeInClassMethod.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ThisType/thisTypeInClassMethod'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ThisType/thisTypeInClassMethodRecorded.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ThisType/thisTypeInClassMethodRecorded'>;
}
declare module 'flow-runtime/lib/__tests__/fixtures.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/fixtures'>;
}
declare module 'flow-runtime/lib/__tests__/fixtures.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/fixtures.test'>;
}
declare module 'flow-runtime/lib/annotateValue.js' {
  declare module.exports: $Exports<'flow-runtime/lib/annotateValue'>;
}
declare module 'flow-runtime/lib/cache.js' {
  declare module.exports: $Exports<'flow-runtime/lib/cache'>;
}
declare module 'flow-runtime/lib/classDecorators.js' {
  declare module.exports: $Exports<'flow-runtime/lib/classDecorators'>;
}
declare module 'flow-runtime/lib/compareTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/compareTypes'>;
}
declare module 'flow-runtime/lib/cyclic.js' {
  declare module.exports: $Exports<'flow-runtime/lib/cyclic'>;
}
declare module 'flow-runtime/lib/declarations/ClassDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ClassDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/Declaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/Declaration'>;
}
declare module 'flow-runtime/lib/declarations/ExtendsDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ExtendsDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/index'>;
}
declare module 'flow-runtime/lib/declarations/ModuleDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ModuleDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/ModuleExportsDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ModuleExportsDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/TypeDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/TypeDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/VarDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/VarDeclaration'>;
}
declare module 'flow-runtime/lib/decorateFunction.js' {
  declare module.exports: $Exports<'flow-runtime/lib/decorateFunction'>;
}
declare module 'flow-runtime/lib/decorateFunction.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/decorateFunction.test'>;
}
declare module 'flow-runtime/lib/decorateGeneratorFunction.js' {
  declare module.exports: $Exports<'flow-runtime/lib/decorateGeneratorFunction'>;
}
declare module 'flow-runtime/lib/errorMessages.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorMessages'>;
}
declare module 'flow-runtime/lib/errorReporting/__tests__/makeJSONError.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/__tests__/makeJSONError.test'>;
}
declare module 'flow-runtime/lib/errorReporting/__tests__/makeTypeError.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/__tests__/makeTypeError.test'>;
}
declare module 'flow-runtime/lib/errorReporting/makeJSONError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/makeJSONError'>;
}
declare module 'flow-runtime/lib/errorReporting/makeTypeError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/makeTypeError'>;
}
declare module 'flow-runtime/lib/errorReporting/makeWarningMessage.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/makeWarningMessage'>;
}
declare module 'flow-runtime/lib/errorReporting/RuntimeTypeError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/RuntimeTypeError'>;
}
declare module 'flow-runtime/lib/flowTypes/$DiffType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$DiffType'>;
}
declare module 'flow-runtime/lib/flowTypes/$FlowFixMeType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$FlowFixMeType'>;
}
declare module 'flow-runtime/lib/flowTypes/$KeysType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$KeysType'>;
}
declare module 'flow-runtime/lib/flowTypes/$ObjMapiType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$ObjMapiType'>;
}
declare module 'flow-runtime/lib/flowTypes/$ObjMapType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$ObjMapType'>;
}
declare module 'flow-runtime/lib/flowTypes/$ShapeType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$ShapeType'>;
}
declare module 'flow-runtime/lib/flowTypes/$SubType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$SubType'>;
}
declare module 'flow-runtime/lib/flowTypes/$SuperType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/$SuperType'>;
}
declare module 'flow-runtime/lib/flowTypes/ClassType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/ClassType'>;
}
declare module 'flow-runtime/lib/flowTypes/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/flowTypes/index'>;
}
declare module 'flow-runtime/lib/getErrorMessage.js' {
  declare module.exports: $Exports<'flow-runtime/lib/getErrorMessage'>;
}
declare module 'flow-runtime/lib/globalContext.js' {
  declare module.exports: $Exports<'flow-runtime/lib/globalContext'>;
}
declare module 'flow-runtime/lib/index.cjs.js' {
  declare module.exports: $Exports<'flow-runtime/lib/index.cjs'>;
}
declare module 'flow-runtime/lib/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/index'>;
}
declare module 'flow-runtime/lib/invariant.js' {
  declare module.exports: $Exports<'flow-runtime/lib/invariant'>;
}
declare module 'flow-runtime/lib/makeError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeError'>;
}
declare module 'flow-runtime/lib/makeReactPropTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeReactPropTypes'>;
}
declare module 'flow-runtime/lib/makeUnion.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeUnion'>;
}
declare module 'flow-runtime/lib/primitiveTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/primitiveTypes'>;
}
declare module 'flow-runtime/lib/registerBuiltins.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerBuiltins'>;
}
declare module 'flow-runtime/lib/registerPrimitiveTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerPrimitiveTypes'>;
}
declare module 'flow-runtime/lib/registerTypePredicates.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerTypePredicates'>;
}
declare module 'flow-runtime/lib/symbols.js' {
  declare module.exports: $Exports<'flow-runtime/lib/symbols'>;
}
declare module 'flow-runtime/lib/typeConstraints.js' {
  declare module.exports: $Exports<'flow-runtime/lib/typeConstraints'>;
}
declare module 'flow-runtime/lib/typeConstraints.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/typeConstraints.test'>;
}
declare module 'flow-runtime/lib/TypeContext.js' {
  declare module.exports: $Exports<'flow-runtime/lib/TypeContext'>;
}
declare module 'flow-runtime/lib/typed.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/typed.test'>;
}
declare module 'flow-runtime/lib/TypeInferrer.js' {
  declare module.exports: $Exports<'flow-runtime/lib/TypeInferrer'>;
}
declare module 'flow-runtime/lib/TypeInferrer.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/TypeInferrer.test'>;
}
declare module 'flow-runtime/lib/types/AnyType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/AnyType'>;
}
declare module 'flow-runtime/lib/types/ArrayType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ArrayType'>;
}
declare module 'flow-runtime/lib/types/BooleanLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/BooleanLiteralType'>;
}
declare module 'flow-runtime/lib/types/BooleanType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/BooleanType'>;
}
declare module 'flow-runtime/lib/types/EmptyType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/EmptyType'>;
}
declare module 'flow-runtime/lib/types/ExistentialType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ExistentialType'>;
}
declare module 'flow-runtime/lib/types/FlowIntoType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FlowIntoType'>;
}
declare module 'flow-runtime/lib/types/FunctionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionType'>;
}
declare module 'flow-runtime/lib/types/FunctionTypeParam.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionTypeParam'>;
}
declare module 'flow-runtime/lib/types/FunctionTypeRestParam.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionTypeRestParam'>;
}
declare module 'flow-runtime/lib/types/FunctionTypeReturn.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionTypeReturn'>;
}
declare module 'flow-runtime/lib/types/GeneratorType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/GeneratorType'>;
}
declare module 'flow-runtime/lib/types/GenericType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/GenericType'>;
}
declare module 'flow-runtime/lib/types/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/index'>;
}
declare module 'flow-runtime/lib/types/IntersectionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/IntersectionType'>;
}
declare module 'flow-runtime/lib/types/MixedType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/MixedType'>;
}
declare module 'flow-runtime/lib/types/NullableType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NullableType'>;
}
declare module 'flow-runtime/lib/types/NullLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NullLiteralType'>;
}
declare module 'flow-runtime/lib/types/NumberType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NumberType'>;
}
declare module 'flow-runtime/lib/types/NumericLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NumericLiteralType'>;
}
declare module 'flow-runtime/lib/types/ObjectType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectType'>;
}
declare module 'flow-runtime/lib/types/ObjectTypeCallProperty.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectTypeCallProperty'>;
}
declare module 'flow-runtime/lib/types/ObjectTypeIndexer.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectTypeIndexer'>;
}
declare module 'flow-runtime/lib/types/ObjectTypeProperty.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectTypeProperty'>;
}
declare module 'flow-runtime/lib/types/ParameterizedFunctionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ParameterizedFunctionType'>;
}
declare module 'flow-runtime/lib/types/ParameterizedTypeAlias.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ParameterizedTypeAlias'>;
}
declare module 'flow-runtime/lib/types/PartialType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/PartialType'>;
}
declare module 'flow-runtime/lib/types/RefinementType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/RefinementType'>;
}
declare module 'flow-runtime/lib/types/StringLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/StringLiteralType'>;
}
declare module 'flow-runtime/lib/types/StringType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/StringType'>;
}
declare module 'flow-runtime/lib/types/SymbolLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/SymbolLiteralType'>;
}
declare module 'flow-runtime/lib/types/SymbolType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/SymbolType'>;
}
declare module 'flow-runtime/lib/types/ThisType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ThisType'>;
}
declare module 'flow-runtime/lib/types/TupleType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TupleType'>;
}
declare module 'flow-runtime/lib/types/Type.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/Type'>;
}
declare module 'flow-runtime/lib/types/TypeAlias.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeAlias'>;
}
declare module 'flow-runtime/lib/types/TypeBox.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeBox'>;
}
declare module 'flow-runtime/lib/types/TypeConstructor.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeConstructor'>;
}
declare module 'flow-runtime/lib/types/TypeParameter.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeParameter'>;
}
declare module 'flow-runtime/lib/types/TypeParameterApplication.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeParameterApplication'>;
}
declare module 'flow-runtime/lib/types/TypeReference.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeReference'>;
}
declare module 'flow-runtime/lib/types/UnionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/UnionType'>;
}
declare module 'flow-runtime/lib/types/VoidType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/VoidType'>;
}
declare module 'flow-runtime/lib/Validation.js' {
  declare module.exports: $Exports<'flow-runtime/lib/Validation'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ThisType/thisTypeInClassMethod.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ThisType/thisTypeInClassMethod'>;
}
declare module 'flow-runtime/src/__tests__/__fixtures__/ThisType/thisTypeInClassMethodRecorded.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/__fixtures__/ThisType/thisTypeInClassMethodRecorded'>;
}
declare module 'flow-runtime/src/__tests__/fixtures.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/fixtures'>;
}
declare module 'flow-runtime/src/__tests__/fixtures.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/__tests__/fixtures.test'>;
}
declare module 'flow-runtime/src/annotateValue.js' {
  declare module.exports: $Exports<'flow-runtime/src/annotateValue'>;
}
declare module 'flow-runtime/src/cache.js' {
  declare module.exports: $Exports<'flow-runtime/src/cache'>;
}
declare module 'flow-runtime/src/classDecorators.js' {
  declare module.exports: $Exports<'flow-runtime/src/classDecorators'>;
}
declare module 'flow-runtime/src/compareTypes.js' {
  declare module.exports: $Exports<'flow-runtime/src/compareTypes'>;
}
declare module 'flow-runtime/src/cyclic.js' {
  declare module.exports: $Exports<'flow-runtime/src/cyclic'>;
}
declare module 'flow-runtime/src/declarations/ClassDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/ClassDeclaration'>;
}
declare module 'flow-runtime/src/declarations/Declaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/Declaration'>;
}
declare module 'flow-runtime/src/declarations/ExtendsDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/ExtendsDeclaration'>;
}
declare module 'flow-runtime/src/declarations/index.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/index'>;
}
declare module 'flow-runtime/src/declarations/ModuleDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/ModuleDeclaration'>;
}
declare module 'flow-runtime/src/declarations/ModuleExportsDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/ModuleExportsDeclaration'>;
}
declare module 'flow-runtime/src/declarations/TypeDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/TypeDeclaration'>;
}
declare module 'flow-runtime/src/declarations/VarDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/src/declarations/VarDeclaration'>;
}
declare module 'flow-runtime/src/decorateFunction.js' {
  declare module.exports: $Exports<'flow-runtime/src/decorateFunction'>;
}
declare module 'flow-runtime/src/decorateFunction.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/decorateFunction.test'>;
}
declare module 'flow-runtime/src/decorateGeneratorFunction.js' {
  declare module.exports: $Exports<'flow-runtime/src/decorateGeneratorFunction'>;
}
declare module 'flow-runtime/src/errorMessages.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorMessages'>;
}
declare module 'flow-runtime/src/errorReporting/__tests__/makeJSONError.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorReporting/__tests__/makeJSONError.test'>;
}
declare module 'flow-runtime/src/errorReporting/__tests__/makeTypeError.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorReporting/__tests__/makeTypeError.test'>;
}
declare module 'flow-runtime/src/errorReporting/makeJSONError.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorReporting/makeJSONError'>;
}
declare module 'flow-runtime/src/errorReporting/makeTypeError.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorReporting/makeTypeError'>;
}
declare module 'flow-runtime/src/errorReporting/makeWarningMessage.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorReporting/makeWarningMessage'>;
}
declare module 'flow-runtime/src/errorReporting/RuntimeTypeError.js' {
  declare module.exports: $Exports<'flow-runtime/src/errorReporting/RuntimeTypeError'>;
}
declare module 'flow-runtime/src/flowTypes/$DiffType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$DiffType'>;
}
declare module 'flow-runtime/src/flowTypes/$FlowFixMeType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$FlowFixMeType'>;
}
declare module 'flow-runtime/src/flowTypes/$KeysType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$KeysType'>;
}
declare module 'flow-runtime/src/flowTypes/$ObjMapiType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$ObjMapiType'>;
}
declare module 'flow-runtime/src/flowTypes/$ObjMapType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$ObjMapType'>;
}
declare module 'flow-runtime/src/flowTypes/$ShapeType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$ShapeType'>;
}
declare module 'flow-runtime/src/flowTypes/$SubType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$SubType'>;
}
declare module 'flow-runtime/src/flowTypes/$SuperType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/$SuperType'>;
}
declare module 'flow-runtime/src/flowTypes/ClassType.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/ClassType'>;
}
declare module 'flow-runtime/src/flowTypes/index.js' {
  declare module.exports: $Exports<'flow-runtime/src/flowTypes/index'>;
}
declare module 'flow-runtime/src/getErrorMessage.js' {
  declare module.exports: $Exports<'flow-runtime/src/getErrorMessage'>;
}
declare module 'flow-runtime/src/globalContext.js' {
  declare module.exports: $Exports<'flow-runtime/src/globalContext'>;
}
declare module 'flow-runtime/src/index.cjs.js' {
  declare module.exports: $Exports<'flow-runtime/src/index.cjs'>;
}
declare module 'flow-runtime/src/index.js' {
  declare module.exports: $Exports<'flow-runtime/src/index'>;
}
declare module 'flow-runtime/src/invariant.js' {
  declare module.exports: $Exports<'flow-runtime/src/invariant'>;
}
declare module 'flow-runtime/src/makeError.js' {
  declare module.exports: $Exports<'flow-runtime/src/makeError'>;
}
declare module 'flow-runtime/src/makeReactPropTypes.js' {
  declare module.exports: $Exports<'flow-runtime/src/makeReactPropTypes'>;
}
declare module 'flow-runtime/src/makeUnion.js' {
  declare module.exports: $Exports<'flow-runtime/src/makeUnion'>;
}
declare module 'flow-runtime/src/primitiveTypes.js' {
  declare module.exports: $Exports<'flow-runtime/src/primitiveTypes'>;
}
declare module 'flow-runtime/src/registerBuiltins.js' {
  declare module.exports: $Exports<'flow-runtime/src/registerBuiltins'>;
}
declare module 'flow-runtime/src/registerPrimitiveTypes.js' {
  declare module.exports: $Exports<'flow-runtime/src/registerPrimitiveTypes'>;
}
declare module 'flow-runtime/src/registerTypePredicates.js' {
  declare module.exports: $Exports<'flow-runtime/src/registerTypePredicates'>;
}
declare module 'flow-runtime/src/symbols.js' {
  declare module.exports: $Exports<'flow-runtime/src/symbols'>;
}
declare module 'flow-runtime/src/typeConstraints.js' {
  declare module.exports: $Exports<'flow-runtime/src/typeConstraints'>;
}
declare module 'flow-runtime/src/typeConstraints.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/typeConstraints.test'>;
}
declare module 'flow-runtime/src/TypeContext.js' {
  declare module.exports: $Exports<'flow-runtime/src/TypeContext'>;
}
declare module 'flow-runtime/src/typed.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/typed.test'>;
}
declare module 'flow-runtime/src/TypeInferrer.js' {
  declare module.exports: $Exports<'flow-runtime/src/TypeInferrer'>;
}
declare module 'flow-runtime/src/TypeInferrer.test.js' {
  declare module.exports: $Exports<'flow-runtime/src/TypeInferrer.test'>;
}
declare module 'flow-runtime/src/types/AnyType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/AnyType'>;
}
declare module 'flow-runtime/src/types/ArrayType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ArrayType'>;
}
declare module 'flow-runtime/src/types/BooleanLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/BooleanLiteralType'>;
}
declare module 'flow-runtime/src/types/BooleanType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/BooleanType'>;
}
declare module 'flow-runtime/src/types/EmptyType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/EmptyType'>;
}
declare module 'flow-runtime/src/types/ExistentialType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ExistentialType'>;
}
declare module 'flow-runtime/src/types/FlowIntoType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/FlowIntoType'>;
}
declare module 'flow-runtime/src/types/FunctionType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/FunctionType'>;
}
declare module 'flow-runtime/src/types/FunctionTypeParam.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/FunctionTypeParam'>;
}
declare module 'flow-runtime/src/types/FunctionTypeRestParam.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/FunctionTypeRestParam'>;
}
declare module 'flow-runtime/src/types/FunctionTypeReturn.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/FunctionTypeReturn'>;
}
declare module 'flow-runtime/src/types/GeneratorType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/GeneratorType'>;
}
declare module 'flow-runtime/src/types/GenericType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/GenericType'>;
}
declare module 'flow-runtime/src/types/index.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/index'>;
}
declare module 'flow-runtime/src/types/IntersectionType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/IntersectionType'>;
}
declare module 'flow-runtime/src/types/MixedType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/MixedType'>;
}
declare module 'flow-runtime/src/types/NullableType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/NullableType'>;
}
declare module 'flow-runtime/src/types/NullLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/NullLiteralType'>;
}
declare module 'flow-runtime/src/types/NumberType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/NumberType'>;
}
declare module 'flow-runtime/src/types/NumericLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/NumericLiteralType'>;
}
declare module 'flow-runtime/src/types/ObjectType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ObjectType'>;
}
declare module 'flow-runtime/src/types/ObjectTypeCallProperty.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ObjectTypeCallProperty'>;
}
declare module 'flow-runtime/src/types/ObjectTypeIndexer.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ObjectTypeIndexer'>;
}
declare module 'flow-runtime/src/types/ObjectTypeProperty.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ObjectTypeProperty'>;
}
declare module 'flow-runtime/src/types/ParameterizedFunctionType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ParameterizedFunctionType'>;
}
declare module 'flow-runtime/src/types/ParameterizedTypeAlias.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ParameterizedTypeAlias'>;
}
declare module 'flow-runtime/src/types/PartialType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/PartialType'>;
}
declare module 'flow-runtime/src/types/RefinementType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/RefinementType'>;
}
declare module 'flow-runtime/src/types/StringLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/StringLiteralType'>;
}
declare module 'flow-runtime/src/types/StringType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/StringType'>;
}
declare module 'flow-runtime/src/types/SymbolLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/SymbolLiteralType'>;
}
declare module 'flow-runtime/src/types/SymbolType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/SymbolType'>;
}
declare module 'flow-runtime/src/types/ThisType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/ThisType'>;
}
declare module 'flow-runtime/src/types/TupleType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TupleType'>;
}
declare module 'flow-runtime/src/types/Type.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/Type'>;
}
declare module 'flow-runtime/src/types/TypeAlias.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TypeAlias'>;
}
declare module 'flow-runtime/src/types/TypeBox.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TypeBox'>;
}
declare module 'flow-runtime/src/types/TypeConstructor.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TypeConstructor'>;
}
declare module 'flow-runtime/src/types/TypeParameter.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TypeParameter'>;
}
declare module 'flow-runtime/src/types/TypeParameterApplication.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TypeParameterApplication'>;
}
declare module 'flow-runtime/src/types/TypeReference.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/TypeReference'>;
}
declare module 'flow-runtime/src/types/UnionType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/UnionType'>;
}
declare module 'flow-runtime/src/types/VoidType.js' {
  declare module.exports: $Exports<'flow-runtime/src/types/VoidType'>;
}
declare module 'flow-runtime/src/Validation.js' {
  declare module.exports: $Exports<'flow-runtime/src/Validation'>;
}
declare module 'flow-runtime/test-polyfill.js' {
  declare module.exports: $Exports<'flow-runtime/test-polyfill'>;
}
