// flow-typed signature: e8b0585d865a4b6433f5718cc1db3487
// flow-typed version: <<STUB>>/eslint-plugin-flow_v0.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flow' {
  declare module.exports: any;
}
