// flow-typed signature: 402f62e28604e028ef63820b1b5c2a25
// flow-typed version: <<STUB>>/flow-config-parser_v^0.3.0/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-config-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-config-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-config-parser/config/eslint' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-config-parser' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/mocha' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/eslint-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/mobx_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/mobx-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-config-parser/src/__tests__/flowConfigParser.test' {
  declare module.exports: any;
}

declare module 'flow-config-parser/src/flowConfigParser' {
  declare module.exports: any;
}

declare module 'flow-config-parser/test-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-config-parser/config/eslint.js' {
  declare module.exports: $Exports<'flow-config-parser/config/eslint'>;
}
declare module 'flow-config-parser/flow-config-parser.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-config-parser'>;
}
declare module 'flow-config-parser/flow-typed/mocha.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/mocha'>;
}
declare module 'flow-config-parser/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/eslint-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/eslint-plugin-flow_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/mobx_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/mobx_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/mobx-react_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/mobx-react_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/mocha_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/mocha_vx.x.x'>;
}
declare module 'flow-config-parser/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'flow-config-parser/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'flow-config-parser/src/__tests__/flowConfigParser.test.js' {
  declare module.exports: $Exports<'flow-config-parser/src/__tests__/flowConfigParser.test'>;
}
declare module 'flow-config-parser/src/flowConfigParser.js' {
  declare module.exports: $Exports<'flow-config-parser/src/flowConfigParser'>;
}
declare module 'flow-config-parser/test-polyfill.js' {
  declare module.exports: $Exports<'flow-config-parser/test-polyfill'>;
}
